### ISSUE TITLE
Unknown value of sensors

### ISSUE THREAD

**Issue by jacekpaszkowski** [bieniu/ha-gios#5]
Hello,

i very often get unknown value of sensors like this:
![image](https://user-images.githubusercontent.com/4264991/65491704-e1c5f200-deaf-11e9-8f39-db607b114172.png)

No errors in ha log.

Please help.

**Comment by bieniu** [comment]
Check your measuring station at http://powietrze.gios.gov.pl/pjp/current/station_details/chart/<STATION_NUMBER> Recently, many measuring stations do not give correct data.

**Comment by bieniu** [comment]
From version [0.4.2](https://github.com/bieniu/ha-gios/releases/tag/0.4.2) sensors with no correct data from server will be unavailable.
